#!/bin/bash
declare -a arr_love=("❡ ❤ the way u type" "☎ me when ur free" "♫ u make my heart sing ♪" "u r my super man" "only u n ❡ tonight" "♥ me ßaby" "♬ sing with me" "u r so hot" "❤ hug me" "kiss me ❤")
declare -a arr_fuck=("Are you serious" "u gotta be kidding" "stop it" "Do not piss me off" "aaahh" "Grrr" "Blah Blah" "muhahaha" "who are u man" "go away bitch")
if [ $1 -eq 0 ]
then
i=$(expr $RANDOM % 10)
echo ${arr_love[$i]}
elif [ $1 -eq 1 ]
then
echo "booo booo"
else
i=$(expr $RANDOM % 10)
echo ${arr_fuck[$i]}
fi
